# Generated by Django 5.1.7 on 2026-06-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
