# Generated by Django 5.1.7 on 2026-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_activation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, default="Kenya", max_length=100, null=True
            ),
        ),
    ]
