# Generated by Django 5.1.7 on 2026-06-15 20:28

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("model", models.CharField(default="gemini", max_length=100)),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=150)),
                ("county", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("maize", "Maize"),
                            ("tea", "Tea"),
                            ("coffee", "Coffee"),
                            ("avocado", "Avocado"),
                            ("rice", "Rice"),
                            ("vegetables", "Vegetables"),
                            ("mixed", "Mixed"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "land_acres",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=10
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("latest_risk_score", models.FloatField(default=0)),
                (
                    "latest_risk_level",
                    models.CharField(default="UNKNOWN", max_length=20),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("score", models.FloatField()),
                ("level", models.CharField(max_length=20)),
                ("drivers", models.JSONField(default=list)),
                ("recommended_actions", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="open_meteo", max_length=50)),
                ("raw_response", models.JSONField()),
                ("current_temperature", models.FloatField(blank=True, null=True)),
                ("max_temperature", models.FloatField(blank=True, null=True)),
                ("min_temperature", models.FloatField(blank=True, null=True)),
                ("max_rainfall", models.FloatField(blank=True, null=True)),
                ("max_wind_speed", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
