# Generated by Django 5.1.7 on 2026-06-15 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_insights",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_assessments",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="risk_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_insights",
                to="farms.riskassessment",
            ),
        ),
        migrations.AddField(
            model_name="weathersnapshot",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_snapshots",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="weather_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="farms.weathersnapshot",
            ),
        ),
    ]
