# Generated by Django 5.1.7 on 2026-06-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm",
            name="contact_phone",
        ),
    ]
